[package]
name = "xla"
version = "0.1.0"
authors = ["laurent <laurent.mazare@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1"
libc = "0.2"
num-traits = "0.2"
num-derive = "0.3"

[build-dependencies]
bindgen = "0.64"
cc = "1.0"

[dev-dependencies]
anyhow = "1.0"
